server:
  port: ${PORT:8080}
  compression:
    enabled: true

spring:
  data:
    elasticsearch:
      repositories:
        enabled: false
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
  jackson:
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false

elasticsearch:
  index: ${ELASTICSEARCH_INDEX:spells-v1}
  monsters-index: ${ELASTICSEARCH_MONSTERS_INDEX:monsters-v1}
